### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by techguy16** [Endermanch/quiet#2]
Can there be a Linux version of the quiet script, because Linux already has Sudo for elevating commands?

**Comment by yum13241** [comment]
Just redirect stdout to /dev/null/?

**Comment by Thatdolphinguy-real** [comment]
Endermanch unblock nestor5cat or i make alt of you

**Comment by techguy16** [comment]
So do I do this?:
`_command_ > /dev/null`

**Comment by yum13241** [comment]
Yes. Also `_command_ > /dev/null 2>&1` also redirects stderr to stdout. The `2>&1` bit does that. The error2output part.

**Comment by techguy16** [comment]
Thanks for the responses :)

**Comment by yum13241** [comment]
You are welcome! (a bit of googling could have gotten your answer faster though)

**Comment by techguy16** [comment]
> You are welcome! (a bit of googling could have gotten your answer faster though)

I probably should've, but I like this way better :)

**Comment by yum13241** [comment]
Heh. Have fun Linuxing!
